[tool.poetry]
name = "xt-exchange-emulator"
version = "0.1.0"
description = ""
authors = ["temapskov <psk@ro.ru>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
